spring:
  datasource:
    url: jdbc:mysql://localhost:3306/house_deed_pavilion?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 以下是Druid连接池的专用配置，连接池参数：initial-size、min-idle、max-active 等参数需要根据你的应用实际负载和数据库承载能力进行调整。
    druid:
      # 连接池基础配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 连接池监控配置
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 过滤器配置
      filters: stat,wall,log4j
      # 监控页面的配置
      stat-view-servlet:
        enabled: true # 启用内置的监控页面
        url-pattern: "/druid/*"
        login-username: admin # 监控页面登录用户名
        login-password: admin # 监控页面登录密码
        reset-enable: false # 禁用重置按钮
        allow:
        deny:
      # Web应用统计配置
      web-stat-filter:
        enabled: true # 启用Web统计功能
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 1000
  application:
    name: HouseDeedPavilion
mybatis:
  # 指定 Mapper XML 文件的位置（支持通配符）
  mapper-locations: classpath:COM/Deed/Pavilion/Mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 开启下划线转驼峰映射
pagehelper:
  helper-dialect: mysql # 数据库方言（根据实际数据库类型配置，如oracle、postgresql等）
  reasonable: true # 分页合理化：当页码小于1时查询第一页，大于总页数时查询最后一页
  support-methods-arguments: true # 支持通过Mapper接口参数传递分页参数
springdoc:
  packages-to-scan: COM.House.Deed.Pavilion.Controller  # 请替换为你的控制器包名
  api-docs:
    path: /v3/api-docs  #  OpenAPI JSON 端点路径
  swagger-ui:
    path: /swagger-ui.html  #  Swagger UI 访问路径
    enabled: true  #  启用 Swagger UI
  # 自定义文档信息
  info:
    contact:
      name: yuquanxi
      url: yuquanxi.site
      email: 753280878@qq.com